executor_00:
  use_composable_nodes: false
  executor_type: "single_threaded_executor"
  nodes:
  - node_name: "simple_talker"
    node_type: simple_talker
    intra_process: false
    callbacks:
      - topic: /topic/message/name0
        frequency: 10
        message: "Hello from name0"
        launch: true
  - node_name: "simple_listener"
    node_type: simple_listener
    intra_process: false
    silent: true
    callbacks:
      - topic: /topic/message/name0


executor_01:
  use_composable_nodes: false
  executor_type: "multi_threaded_executor"
  nodes:
  - node_name: "simple_talker"
    node_type: simple_talker
    intra_process: true
    callbacks:
      - topic: /topic/intra_process/message/name1
        frequency: 10
        message: "Hello from name1 via shared memory"
        launch: true
  - node_name: "simple_listener"
    node_type: simple_listener
    intra_process: true
    silent: true
    callbacks:
      - topic: /topic/message/name0
      - topic: /topic/intra_process/message/name1

executor_02:
  use_composable_nodes: false
  executor_type: "single_threaded_executor"
  nodes:
  - node_name: "simple_talker"
    node_type: simple_talker
    intra_process: false
    callbacks:
      - topic: /topic/intra_process/message/name2
        frequency: 10
        message: "Hello from name2 via shared memory"
        launch: true
  - node_name: "another_simple_talker"
    node_type: simple_talker
    intra_process: true
    callbacks:
      - topic: /topic/message/name3
        frequency: 10
        message: "Hello from name3"
        launch: false
  - node_name: "simple_listener"
    node_type: simple_listener
    intra_process: false
    silent: true
    callbacks:
      - topic: /topic/intra_process/message/name2
  - node_name: "another_simple_listener"
    node_type: simple_listener
    intra_process: true
    silent: true
    callbacks:
      - topic: /topic/message/name3

# Compsable nodes configuration.
composable_executor_00:
  use_composable_nodes: true
  executor_type: "multi_threaded_executor"
  nodes:
  - node_name: "composable_simple_talker"
    node_type: simple_talker
    intra_process: false
    callbacks:
      - topic: /topic/message/composable_name0
        frequency: 1
        message: "Hello from composable_name0"
        launch: true
  - node_name: "composable_simple_listener"
    node_type: simple_listener
    intra_process: false
    silent: true
    callbacks:
      - topic: /topic/message/composable_name0

composable_executor_01:
  use_composable_nodes: true
  executor_type: "multi_threaded_executor"
  nodes:
  - node_name: "composable_simple_talker"
    node_type: simple_talker
    intra_process: true
    callbacks:
      - topic: /topic/intra_process/message/composable_name1
        frequency: 1
        message: "Hello from composable_name1 via shared memory"
        launch: true
  - node_name: "composable_simple_listener"
    node_type: simple_listener
    intra_process: true
    silent: false
    callbacks:
      - topic: /topic/message/composable_name0
      - topic: /topic/intra_process/message/composable_name1
  - node_name: "another_composable_simple_talker"
    node_type: simple_talker
    intra_process: false
    callbacks:
      - topic: /topic/message/composable_name2
        frequency: 10
        message: "Hello from composable_name2"
  - node_name: "another_composable_simple_listener"
    node_type: simple_listener
    intra_process: false
    silent: true
    callbacks:
      - topic: /topic/message/composable_name2
