# 0: sample listener and talker
# callback number is 2 for each talker and listener
a_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /topic/message/name0
      frequency: 10
      message: "Hello from name0"
    - topic: /topic/message/name1
      frequency: 10
      message: "Hello from name1"
    - topic: /topic/message/name2
      frequency: 10
      message: "Hello from name2"
    - topic: /topic/message/name3
      frequency: 10
      message: "Hello from name3"
    - topic: /topic/message/name4
      frequency: 10
      message: "Hello from name4"
    - topic: /topic/message/name5
      frequency: 10
      message: "Hello from name5"
    - topic: /topic/message/name6
      frequency: 10
      message: "Hello from name6"
    - topic: /topic/message/name7
      frequency: 10
      message: "Hello from name7"
    - topic: /topic/message/name8
      frequency: 10
      message: "Hello from name8"
    - topic: /topic/message/name9
      frequency: 10
      message: "Hello from name9"


a_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /topic/message/name0
    - topic: /topic/message/name1
    - topic: /topic/message/name2
    - topic: /topic/message/name3
    - topic: /topic/message/name4
    - topic: /topic/message/name5
    - topic: /topic/message/name6
    - topic: /topic/message/name7
    - topic: /topic/message/name8
    - topic: /topic/message/name9

# 1 : hard rock band #0
# hard rock band talkers and listeners
# callback number is 10 for each talker and listener
hard_rock_band_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /led_zeppelin/message
      frequency: 10
      message: "Immigrant song from led zeppelin"
    - topic: /deep_purple/message
      frequency: 10
      message: "Highway star from deep purple"
    - topic: /pink_floyd/message
      frequency: 10
      message: "Echoes from pink floyd"
    - topic: /queen/message
      frequency: 10
      message: "Killer queen from queen"
    - topic: /kiss/message
      frequency: 10
      message: "Detroit rock city from kiss"
    - topic: /uriah_heep/message
      frequency: 10
      message: "SALISBURY from uriah heep"
    - topic: /rainbow/message
      frequency: 10
      message: "Kill the Kint from rainbow"
    - topic: /scorpions/message
      frequency: 10
      message: "Virgin killer from the scorpions"
    - topic: /thin_lizzy/message
      frequency: 10
      message: "Jailbreak from thin lizzy"
    - topic: /michael_schenker_group/message
      frequency: 10
      message: "Doctor Doctor from michael schenker group"

hard_rock_band_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /led_zeppelin/message
    - topic: /deep_purple/message
    - topic: /pink_floyd/message
    - topic: /queen/message
    - topic: /kiss/message
    - topic: /uriah_heep/message
    - topic: /rainbow/message
    - topic: /scorpions/message
    - topic: /thin_lizzy/message
    - topic: /michael_schenker_group/message

# 2 : hard rock band #1
# hard rock band talkers and listeners
# callback number is 10 for each talker and listener
hard_rock_band_1_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /ac_dc/message
      frequency: 10
      message: "Back in Black from ac/dc"
    - topic: /aerosmith/message
      frequency: 10
      message: "Miss a sing from aerosmith"
    - topic: /black_sabbath/message
      frequency: 10
      message: "war pigs from black sabbath"
    - topic: /grand_funk/message
      frequency: 10
      message: "We're an American band from grand funk railroad"
    - topic: /alice_cooper/message
      frequency: 10
      message: "School's out from alice cooper"
    - topic: /van_halen/message
      frequency: 10
      message: "Jump from van halen"
    - topic: /alcatrazz/message
      frequency: 10
      message: "God bless the child from alcatrazz"
    - topic: /def_leppard/message
      frequency: 10
      message: "Photograph from def leppard"
    - topic: /motley_crue/message
      frequency: 10
      message: "Kickstart my heart from motley crue"
    - topic: /guns_n_roses/message
      frequency: 10
      message: "Sweet child o' mine from guns n' roses"

hard_rock_band_1_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /ac_dc/message
    - topic: /aerosmith/message
    - topic: /black_sabbath/message
    - topic: /grand_funk/message
    - topic: /alice_cooper/message
    - topic: /van_halen/message
    - topic: /alcatrazz/message
    - topic: /def_leppard/message
    - topic: /motley_crue/message
    - topic: /guns_n_roses/message

# 3: hard rock mucisians #0
# hard rock musicians talkers and listeners
# callback number is 10 for each talker and listener
hard_rock_musician_0_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /jimmy_page/message
      frequency: 10
      message: "Hello from jimmy page"
    - topic: /robert_plant/message
      frequency: 10
      message: "Hello from robert plant"
    - topic: /john_bonham/message
      frequency: 10
      message: "Hello from john bonham"
    - topic: /john_paul_jones/message
      frequency: 10
      message: "Hello from john paul jones"
    - topic: /richie_blackmore/message
      frequency: 10
      message: "Hello from richie blackmore"
    - topic: /ian_gillan/message
      frequency: 10
      message: "Hello from ian gillan"
    - topic: /roger_glover/message
      frequency: 10
      message: "Hello from roger glover"
    - topic: /john_lord/message
      frequency: 10
      message: "Hello from john lord"
    - topic: /ian_paice/message
      frequency: 10
      message: "Hello from ian paice"
    - topic: /david_gilmour/message
      frequency: 10
      message: "Hello from david gilmour"


hard_rock_musician_0_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /jimmy_page/message
    - topic: /robert_plant/message
    - topic: /john_bonham/message
    - topic: /john_paul_jones/message
    - topic: /richie_blackmore/message
    - topic: /ian_gillan/message
    - topic: /roger_glover/message
    - topic: /john_lord/message
    - topic: /ian_paice/message
    - topic: /david_gilmour/message

# 4: hard rock musicians #1
# hard rock musicians talkers and listeners
# callback number is 10 for each talker and listener
hard_rock_musician_1_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /roger_waters/message
      frequency: 10
      message: "Hello from roger waters"
    - topic: /nick_mason/message
      frequency: 10
      message: "Hello from nick mason"
    - topic: /richard_wright/message  
      frequency: 10
      message: "Hello from richard wright"
    - topic: /freddie_mercury/message
      frequency: 10
      message: "Hello from freddie mercury"
    - topic: /brian_may/message
      frequency: 10
      message: "Hello from brian may"
    - topic: /roger_taylor/message
      frequency: 10
      message: "Hello from roger taylor"
    - topic: /john_deacon/message
      frequency: 10
      message: "Hello from john deacon"
    - topic: /gene_simmons/message
      frequency: 10
      message: "Hello from gene simmons"
    - topic: /paul_stanley/message
      frequency: 10
      message: "Hello from paul stanley"
    - topic: /ace_frehley/message
      frequency: 10
      message: "Hello from ace frehley"
    - topic: /peter_criss/message
      frequency: 10
      message: "Hello from peter criss"

hard_rock_musician_1_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /roger_waters/message
    - topic: /nick_mason/message
    - topic: /richard_wright/message
    - topic: /freddie_mercury/message
    - topic: /brian_may/message
    - topic: /roger_taylor/message
    - topic: /john_deacon/message
    - topic: /gene_simmons/message
    - topic: /paul_stanley/message
    - topic: /ace_frehley/message
    - topic: /peter_criss/message

# 6: heavy metal band #0
# heavy metal band talkers and listeners
# callback number is 10 for each talker and listener
heavy_metal_band_0_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /iron_maiden/message
      frequency: 10
      message: "Hallowed be thy name from iron maiden"
    - topic: /metallica/message
      frequency: 10
      message: "Enter sandman from metallica"
    - topic: /slayer/message
      frequency: 10
      message: "Raining blood from slayer"
    - topic: /megadeth/message
      frequency: 10
      message: "Peace sells from megadeth"
    - topic: /anthrax/message
      frequency: 10
      message: "Madhouse from anthrax"
    - topic: /judas_priest/message
      frequency: 10
      message: "Breaking the law from judas priest"
    - topic: /venom/message
      frequency: 10
      message: "Black metal from venom"
    - topic: /testament/message
      frequency: 10
      message: "Practice what you preach from testament"
    - topic: /overkill/message
      frequency: 10
      message: "Elimination from overkill"
    - topic: /exodus/message
      frequency: 10
      message: "Toxic waltz from exodus"
heavy_metal_band_0_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /iron_maiden/message
    - topic: /metallica/message
    - topic: /slayer/message
    - topic: /megadeth/message
    - topic: /anthrax/message
    - topic: /judas_priest/message
    - topic: /venom/message
    - topic: /testament/message
    - topic: /overkill/message
    - topic: /exodus/message
# 7: heavy metal band #1
# heavy metal band talkers and listeners
# callback number is 10 for each talker and listener
heavy_metal_band_1_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /bathory/message
      frequency: 10
      message: "Blood Fire Death from bathory"
    - topic: /mayhem/message
      frequency: 10
      message: "Freezing Moon from mayhem"
    - topic: /burzum/message
      frequency: 10
      message: "Dunkelheit from burzum"
    - topic: /darkthrone/message
      frequency: 10
      message: "Transilvanian Hunger from darkthrone"
    - topic: /immortal/message
      frequency: 10
      message: "All Shall Fall from immortal"
    - topic: /enslaved/message
      frequency: 10
      message: "Isa from enslaved"
    - topic: /emperor/message
      frequency: 10
      message: "I Am the Black Wizards from emperor"
    - topic: /dimmu_borgir/message
      frequency: 10
      message: "Progenies of the Great Apocalypse from dimmu borgir"
    - topic: /satyricon/message
      frequency: 10
      message: "Mother North from satyricon"
    - topic: /gorgoroth/message
      frequency: 10
      message: "Carving a Giant from gorgoroth"
heavy_metal_band_1_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /bathory/message
    - topic: /mayhem/message
    - topic: /burzum/message
    - topic: /darkthrone/message
    - topic: /immortal/message
    - topic: /enslaved/message
    - topic: /emperor/message
    - topic: /dimmu_borgir/message
    - topic: /satyricon/message
    - topic: /gorgoroth/message
# 8: heavy metal band #2
# heavy metal band talkers and listeners
# callback number is 10 for each talker and listener
heavy_metal_band_2_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /arch_enemy/message
      frequency: 10
      message: "Nemesis from arch enemy"
    - topic: /children_of_bodom/message
      frequency: 10
      message: "Downfall from children of bodom"
    - topic: /in_flames/message
      frequency: 10
      message: "Only for the weak from in flames"
    - topic: /soilwork/message
      frequency: 10
      message: "Stabbing the Drama from soilwork"
    - topic: /dark_tranquillity/message
      frequency: 10
      message: "Misery's Crown from dark tranquillity"
    - topic: /amorphis/message
      frequency: 10
      message: "House of Sleep from amorphis"
    - topic: /moonspell/message
      frequency: 10
      message: "Opium from moonspell"
    - topic: /my_dying_bride/message
      frequency: 10
      message: "The Cry of Mankind from my dying bride"
    - topic: /paradise_lost/message
      frequency: 10
      message: "One Second from paradise lost"
    - topic: /cathedral/message
      frequency: 10
      message: "Soul Sacrifice from cathedral"
heavy_metal_band_2_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /arch_enemy/message
    - topic: /children_of_bodom/message
    - topic: /in_flames/message
    - topic: /soilwork/message
    - topic: /dark_tranquillity/message
    - topic: /amorphis/message
    - topic: /moonspell/message
    - topic: /my_dying_bride/message
    - topic: /paradise_lost/message
    - topic: /cathedral/message

# 9: heavy metal band #3
# heavy metal band talkers and listeners
# callback number is 10 for each talker and listener
heavy_metal_band_3_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /death/message
      frequency: 10
      message: "Symbolic from death"
    - topic: /cannibal_corpse/message
      frequency: 10
      message: "Hammer Smashed Face from cannibal corpse"
    - topic: /obituary/message
      frequency: 10
      message: "Slowly We Rot from obituary"
    - topic: /morbid_angel/message
      frequency: 10
      message: "Chapel of Ghouls from morbid angel"
    - topic: /napalm_death/message
      frequency: 10
      message: "You Suffer from napalm death"
    - topic: /carcass/message
      frequency: 10
      message: "Heartwork from carcass"
    - topic: /cynic/message
      frequency: 10
      message: "Traced in Air from cynic"
    - topic: /at_the_gates/message
      frequency: 10
      message: "Blinded by Fear from at the gates"
    - topic: /entombed/message
      frequency: 10
      message: "Left Hand Path from entombed"
    - topic: /dismember/message
      frequency: 10
      message: "Skin Her Alive from dismember"

heavy_metal_band_3_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /death/message
    - topic: /cannibal_corpse/message
    - topic: /obituary/message
    - topic: /morbid_angel/message
    - topic: /napalm_death/message
    - topic: /carcass/message
    - topic: /cynic/message
    - topic: /at_the_gates/message
    - topic: /entombed/message
    - topic: /dismember/message
