a_listener:
  type: listener
  executor_type: single_threaded
  callbacks:
    - topic: /topic/message/name0
    - topic: /topic/message/name1


a_talker:
  type: talker
  executor_type: single_threaded
  callbacks:
    - topic: /topic/message/name0
      frequency: 10
      message: "Hello from name0"
    - topic: /topic/message/name1
      frequency: 50
      message: "Hello from name1"


hard_rock_band_talker:
  type: talker
  executor_type: single_threaded
  callbacks:
    - topic: /led_zeppelin/message
      frequency: 10
      message: "Hello from led zeppelin"
    - topic: /deep_purple/message
      frequency: 50
      message: "Hello from deep purple"
    - topic: /pink_floyd/message
      frequency: 10
      message: "Hello from pink floyd"
    - topic: /queen/message
      frequency: 50
      message: "Hello from queen"
    - topic: /kiss/message
      frequency: 10
      message: "Hello from kiss"
    - topic: /uriah_heep/message
      frequency: 50
      message: "Hello from uriah heep"
    - topic: /rainbow/message
      frequency: 10
      message: "Hello from rainbow"
    - topic: /scorpions/message
      frequency: 50
      message: "Hello from the scorpions"
    - topic: /thin_lizzy/message
      frequency: 10
      message: "Hello from thin lizzy"
    - topic: /judas_priest/message
      frequency: 50
      message: "Hello from judas priest"
    - topic: /ac_dc/message
      frequency: 10
      message: "Hello from ac/dc"
    - topic: /aerosmith/message
      frequency: 50
      message: "Hello from aerosmith"

hard_rock_band_listener:
  type: listener
  silent: 1
  executor_type: single_threaded
  callbacks:
    - topic: /led_zeppelin/message
    - topic: /deep_purple/message
    - topic: /pink_floyd/message
    - topic: /queen/message
    - topic: /kiss/message
    - topic: /uriah_heep/message
    - topic: /rainbow/message
    - topic: /scorpions/message
    - topic: /thin_lizzy/message
    - topic: /judas_priest/message
    - topic: /ac_dc/message
    - topic: /aerosmith/message
      


hard_rock_musician_talker:
  type: talker
  executor_type: single_threaded
  callbacks:
    - topic: /jimmy_page/message
      frequency: 10
      message: "Hello from jimmy page"
    - topic: /robert_plant/message
      frequency: 50
      message: "Hello from robert plant"
    - topic: /john_bonham/message
      frequency: 10
      message: "Hello from john bonham"
    - topic: /john_paul_jones/message
      frequency: 50
      message: "Hello from john paul jones"
    - topic: /richie_blackmore/message
      frequency: 50
      message: "Hello from richie blackmore"
    - topic: /ian_gillan/message
      frequency: 10
      message: "Hello from ian gillan"
    - topic: /roger_glover/message
      frequency: 50
      message: "Hello from roger glover"
    - topic: /john_lord/message
      frequency: 10
      message: "Hello from john lord"
    - topic: /ian_paice/message
      frequency: 50
      message: "Hello from ian paice"
    - topic: /david_gilmour/message
      frequency: 10
      message: "Hello from david gilmour"
    - topic: /roger_waters/message
      frequency: 50
      message: "Hello from roger waters"
    - topic: /nick_mason/message
      frequency: 10
      message: "Hello from nick mason"
    - topic: /richard_wright/message  
      frequency: 50
      message: "Hello from richard wright"
    - topic: /freddie_mercury/message
      frequency: 10
      message: "Hello from freddie mercury"
    - topic: /brian_may/message
      frequency: 50
      message: "Hello from brian may"
    - topic: /roger_taylor/message
      frequency: 10
      message: "Hello from roger taylor"
    - topic: /john_deacon/message
      frequency: 50
      message: "Hello from john deacon"
    - topic: /gene_simmons/message
      frequency: 10
      message: "Hello from gene simmons"
    - topic: /paul_stanley/message
      frequency: 50
      message: "Hello from paul stanley"
    - topic: /ace_frehley/message
      frequency: 10
      message: "Hello from ace frehley"
    - topic: /peter_criss/message
      frequency: 50
      message: "Hello from peter criss"

hard_rock_musician_listener:
  type: listener
  executor_type: single_threaded
  silent: 1
  callbacks:
    - topic: /jimmy_page/message
    - topic: /robert_plant/message
    - topic: /john_bonham/message
    - topic: /john_paul_jones/message
    - topic: /richie_blackmore/message
    - topic: /ian_gillan/message
    - topic: /roger_glover/message
    - topic: /john_lord/message
    - topic: /ian_paice/message
    - topic: /david_gilmour/message
    - topic: /roger_waters/message
    - topic: /nick_mason/message
    - topic: /richard_wright/message
    - topic: /freddie_mercury/message
    - topic: /brian_may/message
    - topic: /roger_taylor/message
    - topic: /john_deacon/message
    - topic: /gene_simmons/message
    - topic: /paul_stanley/message
    - topic: /ace_frehley/message
    - topic: /peter_criss/message

enonomist_talker:
  type: talker
  executor_type: single_threaded
  callbacks:
    - topic: /
      frequency: 10
      message: "Hello from economist"