sample_talker:
  type: talker
  executor_type: single_threaded
  callbacks:
    - topic: /topic/message/name0
      frequency: 10
      message: "Hello from name0"
    - topic: /topic/message/name1
      frequency: 10
      message: "Hello from name1"

sample_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /topic/message/name0
    - topic: /topic/message/name1


repeat_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /topic/message/repeat/name0
      frequency: 10
      message_pattern: 1 # 0: As-is 1: Repeat, 2: Random
      message_bytes: 1024 # size of the message in bytes
      message: "This is a repeated message" # message will be repeated


repeat_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /topic/message/repeat/name0


random_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /topic/message/random/name0
      frequency: 10
      message_pattern: 2 # random
      message_bytes: 1024 # 1KBytes
      message: "This is a random message" # message will be located at the beginning of the message
    - topic: /topic/message/random/name1
      frequency: 10
      message_pattern: 2
      message_bytes: 2048 # 2KBytes

random_listener:
  type: listener
  executor_type: single_threaded
  silent: true
  callbacks:
    - topic: /topic/message/random/name0
    - topic: /topic/message/random/name1


mixed_talker:
  type: talker
  executor_type: multi_threaded
  callbacks:
    - topic: /topic/message/mixed/as_is/name0
      frequency: 10
      message_pattern: 0 # as-is
      message: "This is a mixed message with no pattern"
    - topic: /topic/message/mixed/repeat/name0
      frequency: 10
      message_pattern: 1 # repeat
      message_bytes: 1024 # size of the message in bytes
      message: "This is a mixed message"
    - topic: /topic/message/mixed/random/name0
      frequency: 10
      message_pattern: 2 # random
      message_bytes: 2048 #

mixed_listener:
  type: listener
  executor_type: multi_threaded
  silent: true
  callbacks:
    - topic: /topic/message/mixed/name0
    - topic: /topic/message/mixed/name1
    - topic: /topic/message/mixed/name2


# hard rock band talkers and listeners
# callback number is 12 for each talker and listener
hard_rock_band_talker:
  type: talker
  executor_type: single_threaded
  callbacks:
    - topic: /led_zeppelin/message
      frequency: 10
      message: "Immigrant song from led zeppelin"
    - topic: /deep_purple/message
      frequency: 10
      message: "Highway star from deep purple"
    - topic: /pink_floyd/message
      frequency: 10
      message: "Echoes from pink floyd"
    - topic: /queen/message
      frequency: 10
      message: "Killer queen from queen"
    - topic: /kiss/message
      frequency: 10
      message: "Detroit rock city from kiss"
    - topic: /uriah_heep/message
      frequency: 10
      message: "SALISBURY from uriah heep"
    - topic: /rainbow/message
      frequency: 10
      message: "Kill the Kint from rainbow"
    - topic: /scorpions/message
      frequency: 10
      message: "Virgin killer from the scorpions"
    - topic: /thin_lizzy/message
      frequency: 10
      message: "Jailbreak from thin lizzy"
    - topic: /judas_priest/message
      frequency: 10
      message: "Breaking the law from judas priest"
    - topic: /ac_dc/message
      frequency: 10
      message: "Back in Black from ac/dc"
    - topic: /aerosmith/message
      frequency: 10
      message: "Miss a sing from aerosmith"

hard_rock_band_listener:
  type: listener
  executor_type: single_threaded
  silent: true
  callbacks:
    - topic: /led_zeppelin/message
    - topic: /deep_purple/message
    - topic: /pink_floyd/message
    - topic: /queen/message
    - topic: /kiss/message
    - topic: /uriah_heep/message
    - topic: /rainbow/message
    - topic: /scorpions/message
    - topic: /thin_lizzy/message
    - topic: /judas_priest/message
    - topic: /ac_dc/message
    - topic: /aerosmith/message
      
